export const DISPLAY_ALERT = 'SHOW-ALERT';

export const CLEAR_ALERT = 'CLEAR-ALERT';


export const REGISTER_USER_BEGIN = 'REGISTER-USER-BEGIN';   
export const REGISTER_USER_SUCCESS = 'REGISTER-USER-SUCCESS';
export const REGISTER_USER_ERROR = 'REGISTER-USER-ERROR';

export const LOGIN_USER_BEGIN = 'LOGIN-USER-BEGIN';
export const LOGIN_USER_SUCCESS = 'LOGIN-USER-SUCCESS';
export const LOGIN_USER_ERROR = 'LOGIN-USER-ERROR';


export const RESET_USER_BEGIN = 'RESET-USER-BEGIN';
export const RESET_USER_SUCCESS = 'RESET-USER-SUCCESS';
export const RESET_USER_ERROR = 'RESET-USER-ERROR';


export const TOGGLE_SIDEBAR  = 'TOGGLE_SIDEBAR';
export const LOGOUT_USER = 'LOGOUT_USER';

export const FORGOT_PASSWORD_BEGIN = 'FORGOT_PASSWORD_BEGIN';
export const FORGOT_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_SUCCESS';
export const FORGOT_PASSWORD_ERROR = 'FORGOT_PASSWORD_ERROR';

export const UPDATE_USER_BEGIN = 'UPDATE-USER-BEGIN';
export const UPDATE_USER_SUCCESS = 'UPDATE-USER-SUCCESS';
export const UPDATE_USER_ERROR = 'UPDATE-USER-ERROR';




export const CLEAR_VALUE = 'CLEAR_VALUE ';




export const CREATE_JOB_BEGIN = 'CREATE_JOB_BEGIN ';
export const CREATE_JOB_SUCCESS = 'CREATE_JOB_SUCCESS ';
export const CREATE_JOB_ERROR = 'CREATE_JOB_ERROR ';


export const  EDIT_JOB_BEGIN = 'EDIT_JOB_BEGIN ';
export const EDIT_JOB_SUCCESS = 'EDIT_JOB_SUCCESS';
export const EDIT_JOB_ERROR = 'EDIT_JOB_ERROR';


export const GET_JOBS_BEGIN = 'GET_JOBS_BEGIN ';
export const GET_JOBS_SUCCESS = 'GET_JOBS_SUCCESS ';



export const SET_EDIT_JOB = 'SET_EDIT_JOB';
export const DELETE_JOB_BEGIN = 'DELETE_JOB_BEGIN ';


export const SHOW_STATS_BEGIN = 'SHOW_STATS_BEGIN ';
export const SHOW_STATS_SUCCESS = 'SHOW_STATS_SUCCESS ';
export const SHOW_STATS_ERROR = 'SHOW_STATS_ERROR ';


export const HANDLE_CHANGE = 'HANDLE_CHANGE'

export const CLEAR_FILTERS = 'CLEAR_FILTERS'


export const CHANGE_PAGE = 'CHANGE_PAGE'