export const DISPLAY_ALERT = 'SHOW-ALERT';

export const CLEAR_ALERT = 'CLEAR-ALERT';


export const REGISTER_USER_BEGIN = 'REGISTER-USER-BEGIN';
export const REGISTER_USER_SUCCESS = 'REGISTER-USER-SUCCESS';
export const REGISTER_USER_ERROR = 'REGISTER-USER-ERROR';

export const LOGIN_USER_BEGIN = 'LOGIN-USER-BEGIN';
export const LOGIN_USER_SUCCESS = 'LOGIN-USER-SUCCESS';
export const LOGIN_USER_ERROR = 'LOGIN-USER-ERROR';



export const TOGGLE_SIDEBAR  = 'TOGGLE_SIDEBAR';
export const LOGOUT_USER = 'LOGOUT_USER';



export const UPDATE_USER_BEGIN = 'UPDATE-USER-BEGIN';
export const UPDATE_USER_SUCCESS = 'UPDATE-USER-SUCCESS';
export const UPDATE_USER_ERROR = 'UPDATE-USER-ERROR';


export const HANDLE_CHANGE = 'HANDLE_CHANGE ';

export const CLEAR_VALUE = 'CLEAR_VALUE ';




export const CREATE_JOB_BEGIN = 'CREATE_JOB_BEGIN ';
export const CREATE_JOB_SUCCESS = 'CREATE_JOB_SUCCESS ';
export const CREATE_JOB_ERROR = 'CREATE_JOB_ERROR ';





export const GET_JOBS_BEGIN = 'GET_JOBS_BEGIN ';
export const GET_JOBS_SUCCESS = 'GET_JOBS_SUCCESS ';

